# .github/workflows/format.yml
name: Format Check

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  format:
    name: Check code formatting via treefmt
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version-file: go.mod

      - name: Install required formatters
        run: |
          go install mvdan.cc/gofumpt@latest
          go install github.com/daixiang0/gci@latest
          sudo apt-get update && sudo apt-get install -y shellcheck shfmt

      - name: Install treefmt
        run: |
          curl -L https://github.com/numtide/treefmt/releases/latest/download/treefmt-x86_64-unknown-linux-musl -o /usr/local/bin/treefmt
          chmod +x /usr/local/bin/treefmt

      - name: Check formatting (readonly mode)
        run: treefmt --fail-on-change --allow-missing-formatter
